//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMart_home
{
    using System;
    using System.Collections.Generic;
    
    public partial class sofCarMart
    {
        public int Id { get; set; }
        public string MODEL { get; set; }
        public string MAKE { get; set; }
        public string YEAR { get; set; }
        public System.DateTime DATE_OUT { get; set; }
        public System.DateTime DATE_EXP_RETURN { get; set; }
        public System.DateTime DATE_ACTUAL_RETURN { get; set; }
        public decimal AMOUNT_PAID { get; set; }
        public decimal BALANCE { get; set; }
    }
}
