//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personalInformation
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalData
    {
        public int Id { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CAR_MODEL { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public int AGE { get; set; }
        public string RENTAL_DATE { get; set; }
        public string RETURN_DATE { get; set; }
        public string DEPOSIT { get; set; }
        public string LATE_RETURN { get; set; }
        public string BALANCE { get; set; }
        public string TOTAL_PAID { get; set; }
    }
}
